// Generate content/config/compat-matrix.json deterministically from zodiac-sign
// distance (design/05 §A2). A test asserts the committed snapshot matches this.
//   d = min(|i-j|, 12-|i-j|)   i,j = aries..pisces index 0..11
//   d=4 trine(same element)=0.85; d=2 sextile=0.75; d=6 opposition=0.60;
//   d=3 square=0.45; d=0 same sign=0.70; d=1=0.55; d=5=0.50
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const { signs } = JSON.parse(readFileSync(`${root}/content/signs/profiles.json`, 'utf8'))

const DISTANCE_SCORES = { 0: 0.70, 1: 0.55, 2: 0.75, 3: 0.45, 4: 0.85, 5: 0.50, 6: 0.60 }
// per-pair manual tweaks, applied symmetrically on top of the distance score
const OVERRIDES = {}

const order = signs.map((s) => s.id)
const score = (i, j) => {
  const key = `${order[i]}-${order[j]}`
  const rev = `${order[j]}-${order[i]}`
  if (key in OVERRIDES) return OVERRIDES[key]
  if (rev in OVERRIDES) return OVERRIDES[rev]
  return DISTANCE_SCORES[Math.min(Math.abs(i - j), 12 - Math.abs(i - j))]
}

const matrix = {}
order.forEach((a, i) => {
  const row = {}
  order.forEach((b, j) => { row[b] = score(i, j) })
  matrix[a] = row
})

const out = {
  version: '1.0.0',
  _note: 'Generated by scripts/gen-compat.mjs from zodiac distance (design/05 §A2). Do not edit by hand; edit OVERRIDES in the script and run `pnpm gen:compat`.',
  distanceScores: DISTANCE_SCORES,
  overrides: OVERRIDES,
  matrix,
}
writeFileSync(`${root}/content/config/compat-matrix.json`, `${JSON.stringify(out, null, 2)}\n`)
console.log(`wrote compat-matrix.json (${order.length}×${order.length})`)
