// Generate content/config/compat-matrix.json from sign aspects.
// Mirrors src/core/matching.ts elementRelation/DEFAULT_COMPAT_RULES; a test
// asserts the committed snapshot equals the runtime builder (no drift).
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const { signs } = JSON.parse(readFileSync(`${root}/content/signs/profiles.json`, 'utf8'))

const RULES = { same: 0.85, sextile: 0.75, square: 0.45, opposition: 0.6, neutral: 0.55 }

function relation(ai, bi) {
  if (ai === bi) return 'same'
  const steps = Math.min(Math.abs(ai - bi), 12 - Math.abs(ai - bi))
  switch (steps) {
    case 2: return 'sextile'
    case 3: return 'square'
    case 4: return 'same'
    case 6: return 'opposition'
    default: return 'neutral'
  }
}

const order = signs.map((s) => s.id)
const matrix = {}
signs.forEach((a, ai) => {
  const row = {}
  signs.forEach((b, bi) => { row[b.id] = RULES[relation(ai, bi)] })
  matrix[a.id] = row
})

const out = {
  _comment: 'Generated by scripts/gen-compat.mjs from element aspects (design/02 §5.4). Do not edit by hand; run `pnpm gen:compat`.',
  rules: RULES,
  order,
  matrix,
}
writeFileSync(`${root}/content/config/compat-matrix.json`, `${JSON.stringify(out, null, 2)}\n`)
console.log(`wrote compat-matrix.json (${order.length}×${order.length})`)
